from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from rlflow.schemas.component import ComponentSpec


class GinWriter:
    def render(
        self,
        components: dict[str, ComponentSpec],
        resolved_config: dict[str, dict[str, Any]],
    ) -> str:
        imports: set[str] = set()
        base_files: set[str] = set()
        bindings: dict[str, Any] = {}

        for node_id in sorted(components):
            component = components[node_id]
            target = component.compile_target.get("gin", {})
            imports.update(target.get("imports", []))
            base_files.update(target.get("base_files", []))
            static_bindings = target.get("static_bindings", {})
            for key, value in static_bindings.items():
                bindings[key] = value
            for binding, config_path in target.get("bindings", {}).items():
                value = self._config_value(resolved_config[node_id], config_path)
                if value is not _MISSING:
                    bindings[binding] = value

        lines = [
            "# Generated by rl-flow. Edit the workflow instead of this file.",
            "",
        ]
        for module in sorted(imports):
            lines.append(f"import {module}")
        if imports:
            lines.append("")
        for base_file in sorted(base_files):
            lines.append(f"include '{base_file}'")
        if base_files:
            lines.append("")
        for binding in sorted(bindings):
            lines.append(f"{binding} = {self._format_value(bindings[binding])}")
        lines.append("")
        return "\n".join(lines)

    def write(
        self,
        path: Path,
        components: dict[str, ComponentSpec],
        resolved_config: dict[str, dict[str, Any]],
    ) -> None:
        path.write_text(self.render(components, resolved_config), encoding="utf-8")

    def _config_value(self, config: dict[str, Any], dotted_path: str) -> Any:
        current: Any = config
        for part in dotted_path.split("."):
            if not isinstance(current, dict) or part not in current:
                return _MISSING
            current = current[part]
        return current

    def _format_value(self, value: Any) -> str:
        if isinstance(value, str):
            if value.startswith(("@", "%")):
                return value
            return json.dumps(value)
        if isinstance(value, bool):
            return "True" if value else "False"
        if value is None:
            return "None"
        if isinstance(value, (dict, list, tuple)):
            return json.dumps(value, sort_keys=True)
        return str(value)


class _Missing:
    pass


_MISSING = _Missing()
