from __future__ import annotations

from pathlib import Path
from typing import Iterable

import click
from typer.main import get_command

from rlflow.cli import app
from rlflow.registry.builtin import create_default_registry
from rlflow.schemas.component import ComponentSpec, PortSpec


ROOT = Path(__file__).resolve().parents[1]
REFERENCE_DIR = ROOT / "docs" / "reference"


def main() -> None:
    REFERENCE_DIR.mkdir(parents=True, exist_ok=True)
    (REFERENCE_DIR / "cli.md").write_text(generate_cli_reference(), encoding="utf-8")
    (REFERENCE_DIR / "component-catalog.md").write_text(generate_component_catalog(), encoding="utf-8")


def generate_cli_reference() -> str:
    command = get_command(app)
    lines = [
        "# CLI Reference",
        "",
        "<!-- Generated by scripts/generate_docs_reference.py. Do not edit by hand. -->",
        "",
        "The CLI reference is generated from the Typer application in `rlflow.cli`.",
        "",
    ]
    for path, subcommand in _walk_commands(command):
        display = "rlflow" if not path else "rlflow " + " ".join(path)
        lines.extend(_command_section(display, subcommand))
    return "\n".join(lines).rstrip() + "\n"


def _walk_commands(command: click.Command, path: tuple[str, ...] = ()) -> Iterable[tuple[tuple[str, ...], click.Command]]:
    yield path, command
    if isinstance(command, click.Group):
        for name in sorted(command.commands):
            yield from _walk_commands(command.commands[name], (*path, name))


def _command_section(display: str, command: click.Command) -> list[str]:
    lines = [f"## `{display}`", ""]
    if command.help:
        lines.extend([command.help, ""])
    if isinstance(command, click.Group):
        children = sorted(command.commands)
        if children:
            lines.extend(["Subcommands:", ""])
            for child in children:
                lines.append(f"- `{display} {child}`")
            lines.append("")

    arguments = [param for param in command.params if isinstance(param, click.Argument)]
    options = [param for param in command.params if isinstance(param, click.Option)]
    usage_parts = [display]
    if options:
        usage_parts.append("[OPTIONS]")
    usage_parts.extend(_argument_usage(param) for param in arguments)
    if isinstance(command, click.Group):
        usage_parts.append("COMMAND [ARGS]...")
    lines.extend(["Usage:", "", f"```bash\n{' '.join(usage_parts)}\n```", ""])

    if arguments:
        lines.extend(["Arguments:", "", "| Name | Required |", "| --- | --- |"])
        for argument in arguments:
            lines.append(f"| `{argument.name}` | {'yes' if argument.required else 'no'} |")
        lines.append("")

    if options:
        lines.extend(["Options:", "", "| Option | Default | Description |", "| --- | --- | --- |"])
        for option in options:
            opts = ", ".join([*option.opts, *option.secondary_opts])
            default = "" if option.default is None or option.default is False else f"`{option.default}`"
            help_text = (option.help or "").replace("|", "\\|")
            lines.append(f"| `{opts}` | {default} | {help_text} |")
        lines.append("")
    return lines


def _argument_usage(argument: click.Argument) -> str:
    name = (argument.name or "ARG").upper()
    return name if argument.required else f"[{name}]"


def generate_component_catalog() -> str:
    registry = create_default_registry()
    components = sorted(registry.list(), key=lambda item: (item.source, item.kind, item.id))
    lines = [
        "# Component Catalog",
        "",
        "<!-- Generated by scripts/generate_docs_reference.py. Do not edit by hand. -->",
        "",
        "This catalog is generated from the active default component registry.",
        "",
        "| Source | Kind | ID | Display Name |",
        "| --- | --- | --- | --- |",
    ]
    for component in components:
        lines.append(
            f"| `{component.source}` | `{component.kind}` | `{component.id}` | {component.display_name} |"
        )
    lines.append("")

    for component in components:
        lines.extend(_component_section(component))
    return "\n".join(lines).rstrip() + "\n"


def _component_section(component: ComponentSpec) -> list[str]:
    lines = [
        f"## `{component.id}`",
        "",
        f"**Kind:** `{component.kind}`  ",
        f"**Source:** `{component.source}`  ",
        f"**Version:** `{component.version}`",
        "",
    ]
    if component.description:
        lines.extend([component.description, ""])
    lines.extend(_ports_table("Input Ports", component.input_ports))
    lines.extend(_ports_table("Output Ports", component.output_ports))
    lines.extend(_config_table(component))
    return lines


def _ports_table(title: str, ports: list[PortSpec]) -> list[str]:
    lines = [f"### {title}", ""]
    if not ports:
        return [*lines, "None.", ""]
    lines.extend(["| Name | Type | Required | Description |", "| --- | --- | --- | --- |"])
    for port in ports:
        description = port.description.replace("|", "\\|")
        lines.append(f"| `{port.name}` | `{port.type}` | {'yes' if port.required else 'no'} | {description} |")
    lines.append("")
    return lines


def _config_table(component: ComponentSpec) -> list[str]:
    properties = component.config_schema.get("properties", {}) if component.config_schema else {}
    required = set(component.config_schema.get("required", [])) if component.config_schema else set()
    lines = ["### Config Fields", ""]
    if not properties:
        return [*lines, "None.", ""]
    lines.extend(["| Field | Type | Required | Default | Description |", "| --- | --- | --- | --- | --- |"])
    for name in sorted(properties):
        schema = properties[name]
        field_type = _schema_type(schema)
        default = component.defaults.get(name, schema.get("default", ""))
        default_text = f"`{default}`" if default != "" else ""
        description = str(schema.get("description", "")).replace("|", "\\|")
        lines.append(
            f"| `{name}` | `{field_type}` | {'yes' if name in required else 'no'} | {default_text} | {description} |"
        )
    lines.append("")
    return lines


def _schema_type(schema: dict[str, object]) -> str:
    if "type" in schema:
        raw = schema["type"]
        if isinstance(raw, list):
            return " | ".join(str(item) for item in raw)
        return str(raw)
    if "enum" in schema:
        return "enum"
    if "anyOf" in schema:
        return "anyOf"
    return "value"


if __name__ == "__main__":
    main()
